title: socialmediadetox
email:  socialmediadetox@tuta.io
description: >- # this means to ignore newlines until "baseurl:"
  Repo list
domain: socialmediadetox.github.io
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://socialmediadetox.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:slug.html

favicon: "./logo.png" # relative path to site's favicon

theme: jekyll-theme-midnight